import {SUBJECTS,TYPES,initialState,grade,summarize,validateQuestions,validateBackup} from './core.js';
const $=s=>document.querySelector(s),app=$('#app'),e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let db,state,base=[],bank=[],ready=false,cacheReady=false,busy=false,editing=null,filterSubject='全部',filterGroup='全部',filterType='全部',onlyNew=false,toastTimer;
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',3600)}
const req=r=>new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
async function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('xiaoyu-study',1);r.onupgradeneeded=()=>r.result.createObjectStore('data');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.onblocked=()=>reject(Error('请关闭另一个刷题页面后重试。'))})}
async function persist(){const snapshot=structuredClone(state);return new Promise((resolve,reject)=>{const t=db.transaction('data','readwrite');t.objectStore('data').put(snapshot,'state');t.oncomplete=resolve;t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error)})}
function refreshBank(){const map=new Map(base.map(q=>[q.id,q]));state.custom.forEach(q=>map.set(q.id,q));bank=[...map.values()].filter(q=>!state.hidden.includes(q.id))}
async function change(fn){if(busy)return false;busy=true;const previous=structuredClone(state);try{await fn();await persist();refreshBank();render();return true}catch(err){state=previous;refreshBank();toast('保存失败：'+(err.message||'请先导出备份并检查存储空间。'));return false}finally{busy=false}}
function route(){return location.hash.slice(1)||'home'}
function go(r){if(route()===r)render();else location.hash=r}
function pct(s){return s.scored?Math.round(s.correct/s.scored*100)+'%':'—'}
const codes=['01 / POLITICS','02 / ENGLISH','03 / ART'];
function nav(active){return `<nav class="bottom-nav" aria-label="主要导航">${[['home','练习'],['wrong','错题本'],['stats','统计'],['settings','管理']].map(([r,t])=>`<a href="#${r}" class="${active===r?'active':''}" ${active===r?'aria-current="page"':''}>${t}</a>`).join('')}</nav>`}
function shell(content,active='home'){app.innerHTML=`<header class="topbar"><a class="brand" href="#home"><span class="brandmark">✓</span>小宇刷题</a><span class="pill" id="offline-status"></span></header><main>${content}</main>${nav(active)}`;updateStatus()}
const title=(t,s)=>`<div class="intro"><p class="eyebrow">${s}</p><h1>${t}</h1></div>`;
const empty=(t,s)=>`<section class="empty"><span class="empty-icon">✓</span><h2>${t}</h2><p>${s}</p><a href="#home" class="btn">去练习</a></section>`;
function home(){const all=summarize(bank,state);shell(`${title('今天，从哪一科开始？','每天一点，离目标更近一点')}<div class="summary-strip"><div><b>${all.done}</b><span>已练题目</span></div><div><b>${pct(all)}</b><span>作答正确率</span></div><div><b>${all.wrong}</b><span>待复习错题</span></div></div>${state.session?`<button class="resume" data-action="resume"><span><strong>继续上次练习</strong><small>${e(state.session.subject)} · 第 ${state.session.index+1} / ${state.session.ids.length} 题</small></span><b>继续 →</b></button>`:''}<section class="subject-grid">${SUBJECTS.map((s,i)=>{const st=summarize(bank,state,s);return `<button class="subject" data-subject="${s}"><span class="subject-code">${codes[i]}</span><h2>${s}</h2><p>${st.total} 道题 · 已练 ${st.done} 道</p><div class="track"><i style="width:${st.total?st.done/st.total*100:0}%"></i></div><span class="subject-bottom">进入题库 <b>↗</b></span></button>`}).join('')}</section><section class="notice"><h3>先思考，再看答案</h3><p>提交后显示参考答案；答错或空答自动加入错题本。主观题由你对照批改。</p></section><p class="footnote">题目来自你提供的资料 · 当前 ${bank.length} 道 · <a href="#settings">题库说明与备份</a></p>`)}
function selectSubject(s){filterSubject=s;filterGroup='全部';filterType='全部';go('library')}
function selectedBank(){const done=new Set(state.attempts.map(a=>a.questionId));return bank.filter(q=>(filterSubject==='全部'||q.subject===filterSubject)&&(filterGroup==='全部'||q.group===filterGroup)&&(filterType==='全部'||q.type===filterType)&&(!onlyNew||!done.has(q.id)))}
function library(){const groups=[...new Set(bank.filter(q=>filterSubject==='全部'||q.subject===filterSubject).map(q=>q.group))],list=selectedBank();shell(`<a class="back" href="#home">← 返回练习</a>${title(e(filterSubject),'按资料或题型开始练习')}<section class="panel"><div class="field"><label for="group">选择资料</label><select id="group">${['全部',...groups].map(g=>`<option ${g===filterGroup?'selected':''}>${e(g)}</option>`).join('')}</select></div><div class="field"><label for="type">题型</label><select id="type"><option value="全部">全部题型</option>${Object.entries(TYPES).map(([v,t])=>`<option value="${v}" ${v===filterType?'selected':''}>${t}</option>`).join('')}</select></div><label class="check"><input id="only-new" type="checkbox" ${onlyNew?'checked':''}>只练未做过的题目</label><div class="start-summary"><strong>${list.length}</strong><span>道题可练习</span></div><div class="actions"><button class="btn primary" data-action="start" ${!list.length?'disabled':''}>顺序练习</button><button class="btn" data-action="random" ${!list.length?'disabled':''}>随机练习</button></div></section><section class="notice"><h3>按原资料练习</h3><p>历史试卷保留当年的题意和答案。时政题请结合对应年份理解。英语练习使用专升本资料，高起点资料未混入。</p></section>`)}
async function start(ids,subject,mode='顺序练习'){if(!ids.length)return toast('没有符合条件的题目。');if(await change(()=>{state.session={ids,subject,mode,index:0,draft:[],attemptId:null}}))go('quiz')}
function current(){const s=state.session;return s?bank.find(q=>q.id===s.ids[s.index]):null}
function answerText(q,a){return q.options.length?a.map(v=>`${q.type==='boolean'?'':String.fromCharCode(65+Number(v))+'. '}${q.options[Number(v)]}`).join('；'):a.join('\n')}
function quiz(){const s=state.session,q=current();if(!s||!q){go('home');return}const attempt=state.attempts.find(a=>a.id===s.attemptId),submitted=!!attempt;let inputs;
if(q.options.length)inputs=`<div class="options">${q.options.map((o,i)=>{const selected=Array.isArray(s.draft)&&s.draft.includes(String(i));return `<button class="option ${selected?'selected':''} ${submitted&&q.answer.includes(String(i))?'correct-option':''} ${submitted&&selected&&!q.answer.includes(String(i))?'wrong-option':''}" data-option="${i}" aria-pressed="${selected}" ${submitted?'disabled':''}><span class="letter">${q.type==='boolean'?(i===0?'✓':'×'):String.fromCharCode(65+i)}</span><span>${e(o)}</span></button>`}).join('')}</div>`;
else inputs=`<label class="field" for="draft"><span>你的答案</span><textarea id="draft" rows="${q.type==='fill'?2:6}" placeholder="${q.type==='fill'?'填写答案':'写下你的理解或答案要点…'}" ${submitted?'disabled':''}>${e(typeof s.draft==='string'?s.draft:'')}</textarea></label>`;
const result=submitted?`<section class="result ${attempt.correct===false?'incorrect':''}" aria-live="polite"><div class="result-label">${attempt.correct===true?'✓ 回答正确':attempt.correct===false?(state.wrong[q.id]?'已加入错题本':'本次回答需复习'):'请对照答案，自行批改'}</div><h3>参考答案</h3><div class="prose">${e(answerText(q,q.answer))}</div><h3>解析</h3><div class="prose">${e(q.explanation||'原资料未提供单独解析，请对照参考答案复习。')}</div>${!['single','multiple','boolean','fill'].includes(q.type)?`<div class="actions"><button class="btn" data-action="mark-correct">${attempt.correct===true?'✓ ':''}答对了</button><button class="btn" data-action="mark-wrong">${attempt.correct===false?'✓ ':''}需复习</button></div>`:''}<button class="text-btn" data-action="toggle-wrong">${state.wrong[q.id]?'已掌握，从错题本移除':'加入错题本'}</button></section>`:'';
shell(`<div class="quiz-top"><a href="#${s.mode==='错题复习'?'wrong':'home'}" class="back">← 暂停练习</a><span>${s.index+1} <span class="muted">/ ${s.ids.length}</span></span></div><div class="progress-line"><i style="width:${(s.index+1)/s.ids.length*100}%"></i></div><div class="question-meta"><span class="tag">${e(q.subject)}</span><span>${TYPES[q.type]}</span><span>${e(s.mode)}</span></div><article class="question"><p class="source">${e(q.group)} · 原题 ${e(q.number)}</p>${q.context?`<details class="reading" open><summary>阅读材料</summary><div class="prose">${e(q.context)}</div></details>`:''}<h1 class="stem">${e(q.stem)}</h1>${q.type==='multiple'?'<p class="muted">请选择所有正确选项，选完后提交。</p>':''}${inputs}${result}<div class="quiz-actions">${!submitted?'<button class="btn primary full" data-action="submit">提交答案</button>':`<button class="btn primary full" data-action="next">${s.index+1===s.ids.length?'完成练习':'下一题 →'}</button>`}</div><p class="footnote">来源：${e(q.source)}</p></article>`)}
async function submit(){const q=current(),s=state.session;if(!q||s.attemptId)return;const answer=q.options.length?s.draft:($('#draft')?.value||'');await change(()=>{s.draft=answer;const a={id:crypto.randomUUID(),questionId:q.id,answer:structuredClone(answer),correct:grade(q,answer),time:Date.now()};state.attempts.push(a);s.attemptId=a.id;if(a.correct===false)state.wrong[q.id]=Date.now()});$('.result')?.scrollIntoView({behavior:'smooth',block:'nearest'})}
async function next(){const s=state.session;if(!s?.attemptId)return;if(await change(()=>{if(s.index+1>=s.ids.length)state.session=null;else{s.index++;s.draft=[];s.attemptId=null}})){if(!state.session){go('stats');toast('本轮练习完成，记录已保存。')}else window.scrollTo(0,0)}}
function wrong(){const qs=bank.filter(q=>state.wrong[q.id]&&(filterSubject==='全部'||q.subject===filterSubject));shell(`${title('把错题，变成得分题','错题本')}<div class="chips">${['全部',...SUBJECTS].map(s=>`<button data-wrong-subject="${s}" class="chip ${s===filterSubject?'active':''}">${s}</button>`).join('')}</div>${qs.length?`<div class="list-top"><span>${qs.length} 道待复习</span><button class="btn primary" data-action="review-all">全部重做</button></div><div class="question-list">${qs.map(q=>`<div class="question-row"><button class="question-link" data-review="${q.id}"><span class="source">${e(q.subject)} · ${TYPES[q.type]}</span><strong>${e(q.stem)}</strong><small>${e(q.group)}</small></button><button class="text-btn remove" aria-label="移除错题" data-remove-wrong="${q.id}">移除</button></div>`).join('')}</div><button class="text-btn danger" data-action="clear-wrong">清空${filterSubject==='全部'?'全部':filterSubject}错题</button>`:empty('这里暂时没有错题','答错或空答的题目会保存在这里，答对后也不会自动删除。')}`,'wrong')}
function stats(){const all=summarize(bank,state);shell(`${title('每一道题，都算数','学习统计')}<div class="summary-strip"><div><b>${all.attempts}</b><span>累计作答次数</span></div><div><b>${all.done}</b><span>已练不同题目</span></div><div><b>${pct(all)}</b><span>作答正确率</span></div></div><section class="panel">${SUBJECTS.map(s=>{const x=summarize(bank,state,s);return `<div class="stat-row"><div class="list-top"><h3>${s}</h3><span>${x.done} / ${x.total} 题</span></div><div class="track"><i style="width:${x.total?x.done/x.total*100:0}%"></i></div><p>正确率 ${pct(x)} <span>·</span> 作答 ${x.attempts} 次 <span>·</span> 错题 ${x.wrong} 道</p></div>`}).join('')}</section><section class="notice"><h3>统计如何计算</h3><p>正确率按已判定的作答次数计算，空答记为错误。未自行批改的主观题不计入正确率；重复练习会增加作答次数，不重复增加已练题目数。</p></section>`,'stats')}
function settings(){shell(`${title('你的题库，你的进度','管理与备份')}<section class="panel"><h3>离线使用</h3><p id="offline-detail">${cacheReady?'应用和内置题库已下载，可以断网练习。':'正在准备应用和题库，完成前请保持联网。'}</p><div class="actions"><button class="btn" data-action="prepare">检查离线状态</button></div><ol class="guide"><li>在 iPhone 的 Safari 中打开本应用。</li><li>点分享按钮，选择“添加到主屏幕”。</li><li>从桌面图标打开，等待右上角显示“已可离线”。</li><li>开启飞行模式，重新打开并做一道题，确认可用。</li></ol></section><section class="panel"><h3>学习记录备份</h3><p>记录仅保存在当前设备。清除浏览器数据、删除应用或存储空间不足时可能丢失，请定期导出备份。</p><div class="actions"><button class="btn primary" data-action="backup">导出完整备份</button><label class="btn file-btn">恢复备份<input type="file" id="restore-file" accept=".json,application/json"></label></div><p class="footnote">备份包含题库和记录，请保存在“文件”中，也可通过微信转存。</p></section><section class="panel"><h3>题库管理</h3><p>当前 ${bank.length} 道题。可新增、修改、删除，或导入标准 JSON 题库。</p><div class="actions"><button class="btn" data-action="manage">管理题目</button><label class="btn file-btn">导入题库<input type="file" id="import-file" accept=".json,application/json"></label><button class="text-btn" data-action="template">下载导入模板</button></div></section><section class="panel"><h3>资料整理说明</h3><p>题干、答案与解析均整理自你提供的文件。只将题目结构和答案可以对应的内容纳入练习；扫描件、讲义及未能可靠拆题的内容列入整理清单，未冒充为已导入题目。</p><p>英语按专升本资料整理。历史试卷中的时政内容保留原年份；原资料未提供解析时不补造。</p><a class="text-btn" href="./coverage.json" download="题库整理清单.json">下载资料整理清单</a></section><section class="panel"><h3>无需订阅与调用费用</h3><p>刷题、判分和保存记录都在本机完成，不调用付费 AI 接口。</p><p class="footnote">小宇刷题 · 1.0 · 本地数据模式</p></section>`,'settings')}
function manage(){shell(`<a href="#settings" class="back">← 返回管理</a>${title('题目管理','增删修改只影响当前设备')}<div class="actions"><button class="btn primary" data-action="new-question">新增题目</button><input id="search-question" type="search" placeholder="搜索题干" aria-label="搜索题干"></div><div id="manage-list"></div>`,'settings');manageList('')}
function manageList(search){const list=bank.filter(q=>q.stem.toLowerCase().includes(search.toLowerCase())).slice(0,80);$('#manage-list').innerHTML=`<p class="footnote">显示前 ${list.length} 道匹配题目</p><div class="question-list">${list.map(q=>`<div class="question-row"><button class="question-link" data-edit="${q.id}"><span class="source">${e(q.subject)} · ${TYPES[q.type]}</span><strong>${e(q.stem)}</strong></button><button class="text-btn danger" data-delete="${q.id}">删除</button></div>`).join('')}</div>`}
function editor(id){editing=id?bank.find(q=>q.id===id):null;const q=editing||{subject:'政治',type:'single',stem:'',options:['','','',''],answer:[],explanation:'',source:'自建题目',group:'自建题库',context:''};shell(`<a class="back" href="#manage">← 返回题目管理</a>${title(editing?'编辑题目':'新增题目','填写完整内容后保存')}<form id="editor" class="panel"><div class="two-col"><label class="field">科目<select name="subject">${SUBJECTS.map(s=>`<option ${s===q.subject?'selected':''}>${s}</option>`).join('')}</select></label><label class="field">题型<select name="type">${Object.entries(TYPES).map(([v,t])=>`<option value="${v}" ${v===q.type?'selected':''}>${t}</option>`).join('')}</select></label></div><label class="field">题干<textarea required name="stem" rows="4">${e(q.stem)}</textarea></label><label class="field">阅读材料（可选）<textarea name="context" rows="4">${e(q.context)}</textarea></label><label class="field">选项（每行一个，不加 A/B 编号；判断题填“正确”“错误”）<textarea name="options" rows="4">${e(q.options.join('\n'))}</textarea></label><label class="field">答案<textarea required name="answer" rows="3">${e(q.options.length?q.answer.map(a=>String.fromCharCode(65+Number(a))).join(','):q.answer.join('\n||\n'))}</textarea><small>选择题填 A 或 A,C；填空题的等价答案用 || 分隔；主观题填写完整参考答案。</small></label><label class="field">解析（可选）<textarea name="explanation" rows="5">${e(q.explanation)}</textarea></label><label class="field">资料分组<input required name="group" value="${e(q.group)}"></label><label class="field">来源<input name="source" value="${e(q.source)}"></label><button type="submit" class="btn primary full">保存题目</button></form>`,'settings')}
async function saveEditor(form){const d=Object.fromEntries(new FormData(form)),choice=['single','multiple','boolean'].includes(d.type);try{if(choice&&!/^[A-J](?:[,，\s]+[A-J])*$/.test(d.answer.trim().toUpperCase()))throw Error('选择题答案请填 A 或 A,C。');const options=choice?d.options.split('\n').map(s=>s.trim()).filter(Boolean):[],answer=choice?d.answer.trim().toUpperCase().split(/[,，\s]+/).map(s=>String(s.charCodeAt(0)-65)):d.type==='fill'?d.answer.split('||').map(s=>s.trim()):[d.answer.trim()];const q=validateQuestions([{...d,id:editing?.id||'custom-'+crypto.randomUUID(),options,answer,number:editing?.number||'自建'}])[0];if(await change(()=>{state.custom=state.custom.filter(x=>x.id!==q.id).concat(q);state.session=null})){go('manage');toast('题目已保存。')}}catch(err){toast(err.message)}}
function download(obj,name){const url=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}
function confirmAction(message){return new Promise(resolve=>{const dialog=document.createElement('dialog');dialog.className='confirm-dialog';dialog.innerHTML=`<form method="dialog"><h3>请确认</h3><p>${e(message)}</p><div class="actions"><button class="btn" value="cancel" autofocus>取消</button><button class="btn primary" value="confirm">确认</button></div></form>`;document.body.append(dialog);dialog.addEventListener('close',()=>{const ok=dialog.returnValue==='confirm';dialog.remove();resolve(ok)},{once:true});dialog.showModal()})}
async function readFile(file){if(!file)return null;if(file.size>20*1024*1024)throw Error('文件超过 20 MB，请拆分后导入。');return JSON.parse(await file.text())}
function render(){if(!ready)return;const r=route();if(r==='library')library();else if(r==='quiz')quiz();else if(r==='wrong')wrong();else if(r==='stats')stats();else if(r==='settings')settings();else if(r==='manage')manage();else if(r==='edit')editor(editing?.id);else home()}
function updateStatus(){const el=$('#offline-status');if(el)el.textContent=cacheReady?(navigator.onLine?'已可离线':'离线练习中'):(navigator.onLine?'离线准备中':'离线未就绪')}
async function prepareOffline(){try{if(!('serviceWorker'in navigator))throw Error('请用 Safari 或支持离线应用的浏览器打开。');const reg=await navigator.serviceWorker.register('./sw.js');await navigator.serviceWorker.ready;const worker=reg.active||navigator.serviceWorker.controller;const channel=new MessageChannel();const result=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('离线检查超时，请保持联网重试。')),12000);channel.port1.onmessage=ev=>{clearTimeout(timer);resolve(ev.data)};worker.postMessage({type:'CHECK_CACHE'},[channel.port2])});cacheReady=!!result.ready;if(!cacheReady)throw Error('离线文件不完整，请联网刷新后重试。');updateStatus();if($('#offline-detail'))$('#offline-detail').textContent='应用和内置题库已下载，可以断网练习。';navigator.storage?.persist?.().catch(()=>{});}catch(err){cacheReady=false;updateStatus();if($('#offline-detail'))$('#offline-detail').textContent=err.message;}}
document.addEventListener('click',async ev=>{const b=ev.target.closest('button');if(!b||busy)return;
if(b.dataset.subject)return selectSubject(b.dataset.subject);
if(b.dataset.wrongSubject){filterSubject=b.dataset.wrongSubject;return render()}
if(b.dataset.option!==undefined){const q=current();if(!q||state.session.attemptId)return;const v=b.dataset.option;await change(()=>{let a=Array.isArray(state.session.draft)?state.session.draft:[];state.session.draft=q.type==='multiple'?(a.includes(v)?a.filter(x=>x!==v):[...a,v]):[v]});return}
if(b.dataset.review)return start([b.dataset.review],bank.find(q=>q.id===b.dataset.review).subject,'错题复习');
if(b.dataset.removeWrong){if(await confirmAction('确认已掌握这道题，并从错题本移除？'))await change(()=>delete state.wrong[b.dataset.removeWrong]);return}
if(b.dataset.edit){editing=bank.find(q=>q.id===b.dataset.edit);go('edit');return}
if(b.dataset.delete){if(await confirmAction('删除这道题及其练习记录？此操作仅影响当前设备。'))await change(()=>{const id=b.dataset.delete;state.hidden.push(id);state.custom=state.custom.filter(q=>q.id!==id);state.attempts=state.attempts.filter(a=>a.questionId!==id);delete state.wrong[id];state.session=null});return}
const a=b.dataset.action;
if(a==='start'||a==='random'){let ids=selectedBank().map(q=>q.id);if(a==='random')for(let i=ids.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[ids[i],ids[j]]=[ids[j],ids[i]]}return start(ids,filterSubject,a==='random'?'随机练习':'顺序练习')}
if(a==='resume')go('quiz');if(a==='submit')await submit();if(a==='next')await next();
if(a==='mark-correct'||a==='mark-wrong')await change(()=>{const at=state.attempts.find(x=>x.id===state.session?.attemptId);if(at){at.correct=a==='mark-correct';if(!at.correct)state.wrong[at.questionId]=Date.now()}});
if(a==='toggle-wrong'){const id=current()?.id;if(!id)return;if(state.wrong[id]&&!await confirmAction('确认已掌握，从错题本移除？'))return;await change(()=>{if(state.wrong[id])delete state.wrong[id];else state.wrong[id]=Date.now()})}
if(a==='review-all')return start(bank.filter(q=>state.wrong[q.id]&&(filterSubject==='全部'||q.subject===filterSubject)).map(q=>q.id),filterSubject,'错题复习');
if(a==='clear-wrong'&&await confirmAction('确认清空当前分类的错题？练习记录会保留。'))await change(()=>{bank.filter(q=>filterSubject==='全部'||q.subject===filterSubject).forEach(q=>delete state.wrong[q.id])});
if(a==='backup')download({format:'xiaoyu-study-backup',version:1,exportedAt:new Date().toISOString(),questions:bank,state:{attempts:state.attempts,wrong:state.wrong}},'小宇刷题备份-'+new Date().toISOString().slice(0,10)+'.json');
if(a==='template')download({questions:[{id:'my-question-001',subject:'政治',type:'single',group:'自建题库',stem:'请替换为你的题干',options:['选项一','选项二','选项三','选项四'],answer:['0'],explanation:'请填写原资料解析',source:'老师提供的资料'}]},'题库导入模板.json');
if(a==='prepare'){await prepareOffline();toast(cacheReady?'离线检查通过，请在手机开启飞行模式试用。':'离线尚未就绪，请保持联网后重试。')}
if(a==='manage')go('manage');if(a==='new-question'){editing=null;go('edit')}
});
document.addEventListener('change',async ev=>{const el=ev.target;if(el.id==='group'){filterGroup=el.value;render()}if(el.id==='type'){filterType=el.value;render()}if(el.id==='only-new'){onlyNew=el.checked;render()}
if(el.id==='import-file'||el.id==='restore-file'){try{const data=await readFile(el.files[0]);if(!data)return;if(el.id==='restore-file'){const restored=validateBackup(data);if(await confirmAction(`恢复 ${restored.bank.length} 道题和 ${restored.state.attempts.length} 条作答记录？当前题库与记录将被替换，请先备份。`)){if(await change(()=>{state=restored.state;state.hidden=base.filter(q=>!restored.bank.some(x=>x.id===q.id)).map(q=>q.id)}))toast('备份已恢复。')}}else{const rows=validateQuestions(data),existing=rows.filter(q=>bank.some(x=>x.id===q.id)).length;if(await confirmAction(`导入 ${rows.length} 道题，其中 ${existing} 道将更新同编号题目。是否继续？`)){if(await change(()=>{const ids=new Set(rows.map(q=>q.id));state.custom=state.custom.filter(q=>!ids.has(q.id)).concat(rows);state.hidden=state.hidden.filter(id=>!ids.has(id));state.session=null}))toast('题库已导入，可离线练习。')}}}catch(err){toast('导入失败：'+err.message)}el.value=''}
});
document.addEventListener('input',ev=>{if(ev.target.id==='draft'&&state.session&&!state.session.attemptId){state.session.draft=ev.target.value;persist().catch(()=>toast('草稿保存失败，请导出备份并检查存储空间。'))}if(ev.target.id==='search-question')manageList(ev.target.value)});
document.addEventListener('submit',ev=>{if(ev.target.id==='editor'){ev.preventDefault();saveEditor(ev.target)}});
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0)});window.addEventListener('online',updateStatus);window.addEventListener('offline',updateStatus);
async function boot(){try{db=await openDB();state=await req(db.transaction('data').objectStore('data').get('state'))||initialState();const response=await fetch('./bank.json');if(!response.ok)throw Error('题库下载失败，请保持联网并刷新。');base=validateQuestions(await response.json());refreshBank();ready=true;render();prepareOffline();
const context=document.modelContext;if(context?.registerTool)Promise.resolve(context.registerTool({name:'read_study_summary',title:'查看学习统计',description:'读取本机各科学习进度，不显示题目答案。',inputSchema:{type:'object',properties:{subject:{type:'string',enum:SUBJECTS}},additionalProperties:false},annotations:{readOnlyHint:true},execute:input=>{if(input?.subject&&!SUBJECTS.includes(input.subject))throw Error('无效科目');return summarize(bank,state,input?.subject)}})).catch(()=>{});
}catch(err){shell(`${title('暂时无法打开','小宇刷题')}<section class="panel"><p>${e(err.message)}</p><button class="btn primary" onclick="location.reload()">重新加载</button></section>`,'home')}}boot();
